# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_bidder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
