# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctionhouse', '0003_auto_20180328_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ends',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
